### PR TITLE
Add raw string supporting

### PR DESCRIPTION
**Pull request by suutaku**
add raw svg supporting

### CODE REVIEW

**Comment by yang-f** [comment]
Would you like add a demo?

**Comment by suutaku** [comment]
> Would you like add a demo?
something like:
```dart
import 'package:flutter_svg_provider/flutter_svg_provider.dart';

Image(
  width: 32,
  height: 32,
  image: Svg('<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="391" height="391" viewBox="-70.5 -70.5 391 391" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<rect fill="#fff" stroke="#000" x="-70" y="-70" width="390" height="390"/>
<g opacity="0.8">
	<rect x="25" y="25" width="200" height="200" fill="lime" stroke-width="4" stroke="pink" />
	<circle cx="125" cy="125" r="75" fill="orange" />
	<polyline points="50,150 50,200 200,200 200,100" stroke="red" stroke-width="4" fill="none" />
	<line x1="50" y1="50" x2="200" y2="200" stroke="blue" stroke-width="4" />
</g>
</svg>'
)
```

**Comment by suutaku** [comment]
just update `readme` with a simple example

**Comment by yang-f** [comment]
> just update `readme` with a simple example

here: https://github.com/yang-f/flutter_svg_provider/blob/master/example/lib/main.dart

**Pull request merged**
